version: 2.0
jobs:
  test:
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - checkout
      - run:
          name: test
          command: 
            gradle test
      - persist_to_workspace:
          root: .
          paths: 
            - .
      - store_test_results:
          path: build/test-results
  package:
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - checkout
      - run:
          name: package
          command: 
            gradle jar
      - attach_workspace:
          at: .
      - store_artifacts:
          path: build/libs
          destination: prefix
      - persist_to_workspace:
          root: .
          paths:
            - .
workflows:
  version: 2
  do_stuff:
    jobs:
      - test
      - package