version: 2.0
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - checkout
      - run:
          name: test
          command: 
            gradle test
      - store_test_results:
          path: build/test-results
    test:
      docker:
      - image: circleci/openjdk:8-jdk
      - run:
          name: package
          command: 
            gradle jar  
      - store_artifacts:
          path: build/libs
          destination: prefix
workflow:
  version: 2
  do_stuff:
    jobs:
      - job-1
      - job-2